package by.htp.pay_syst.command;

public enum CommandName {
	AUTHORIZATION, 
	NO_SUCH_COMMAND, 
	ACCOUNT_REFILL, 
	PAYMENT,
	REGISTRATION, 
	ADD_CARD, 
	DELETE_USER, 
	REGISTRATION_ADMIN, 
	LOCK_ACCOUNT,
	UNLOCK_ACCOUNT, 
//	CORRECTION_DATA,
	GET_ACCOUNTS_CARDS,
	CORRECTION_LOGIN,
	CORRECTION_PASSWORD,
	CORRECTION_NAME,
	CORRECTION_SURNAME,
	CORRECTION_ADDRESS,
	CORRECTION_CODEWORD,
	CORRECTION_PHONE_NUMBER,
	CORRECTION_RESIDENCE_REGISTRATION,
	FORGET_PASSWORD,
	TRANSFER_BETWEEN_USERS_CARDS,
	
	
	CORRECT_SERIES_NUMB_PASSPORT,
	CORRECT_IDENTIFIC_NUMB_PASSPORT,
	GET_ACCOUNTS,
	GET_CARDS,
	GET_USERS,
	ADD_NEW_NAME_CARD,
	DELETE_NAME_CARD,
	GET_ALL_NAME_CARD,
	
	LOCALIZATION,
	
	
	GO_TO_CORRECT_DATA,	
	GO_TO_LOCK_ACCOUNT,
	GO_TO_MAIN,
	GO_TO_MAIN_LOC,
	GO_TO_MAIN_ACCOUNT,
	GO_TO_PAGE_ADD_CARD,
	GO_TO_PAYMENT,
	GO_TO_REFILL,
	GO_TO_REGISTRATION,
	GO_TO_REGISTRATION_ADMIN,
	GO_TO_UNLOCK_ACCOUNT,
	GO_TO_ADMIN_CORRECTION_DATA,
	GO_TO_CORRECTION_PASSWORD,
	GO_TO_FORGET_PASSWORD,
	GO_TO_TRANSFER_BETWEEN_CARDS,
	GO_TO_ADMIN_MAIN_ACCOUNT,
	
	

	
	
	
}
